# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: includes/enums/playback_method_enum.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='includes/enums/playback_method_enum.proto',
  package='',
  serialized_pb='\n)includes/enums/playback_method_enum.proto\"\x96\x01\n\x14playback_method_enum\"~\n\x0ePlaybackMethod\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x11\n\rAUTO_SOUND_ON\x10\x01\x12\x12\n\x0e\x41UTO_SOUND_OFF\x10\x02\x12\x11\n\rCLICK_TO_PLAY\x10\x03\x12\r\n\tMOUSEOVER\x10\x04\x12\x16\n\x12\x41UTO_SOUND_UNKNOWN\x10\x05\x42,\n*com.appnexus.data.protobuf.generated.enums')



_PLAYBACK_METHOD_ENUM_PLAYBACKMETHOD = _descriptor.EnumDescriptor(
  name='PlaybackMethod',
  full_name='playback_method_enum.PlaybackMethod',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUTO_SOUND_ON', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUTO_SOUND_OFF', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLICK_TO_PLAY', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOUSEOVER', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUTO_SOUND_UNKNOWN', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=70,
  serialized_end=196,
)


_PLAYBACK_METHOD_ENUM = _descriptor.Descriptor(
  name='playback_method_enum',
  full_name='playback_method_enum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PLAYBACK_METHOD_ENUM_PLAYBACKMETHOD,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=46,
  serialized_end=196,
)

_PLAYBACK_METHOD_ENUM_PLAYBACKMETHOD.containing_type = _PLAYBACK_METHOD_ENUM;
DESCRIPTOR.message_types_by_name['playback_method_enum'] = _PLAYBACK_METHOD_ENUM

class playback_method_enum(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLAYBACK_METHOD_ENUM

  # @@protoc_insertion_point(class_scope:playback_method_enum)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n*com.appnexus.data.protobuf.generated.enums')
# @@protoc_insertion_point(module_scope)
