# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: includes/enums/view_non_measurable_reason_enum.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='includes/enums/view_non_measurable_reason_enum.proto',
  package='',
  serialized_pb='\n4includes/enums/view_non_measurable_reason_enum.proto\"\xb0\x01\n\x1fview_non_measurable_reason_enum\"\x8c\x01\n\x17ViewNonMeasurableReason\x12\x12\n\x0eNOT_APPLICABLE\x10\x00\x12\x15\n\x11SCRIPT_NOT_SERVED\x10\x01\x12\x16\n\x12NO_SCRIPT_CALLBACK\x10\x02\x12\x18\n\x14TECHNICAL_LIMITATION\x10\x03\x12\x14\n\x07UNKNOWN\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x42,\n*com.appnexus.data.protobuf.generated.enums')



_VIEW_NON_MEASURABLE_REASON_ENUM_VIEWNONMEASURABLEREASON = _descriptor.EnumDescriptor(
  name='ViewNonMeasurableReason',
  full_name='view_non_measurable_reason_enum.ViewNonMeasurableReason',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOT_APPLICABLE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCRIPT_NOT_SERVED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_SCRIPT_CALLBACK', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TECHNICAL_LIMITATION', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=4, number=-1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=93,
  serialized_end=233,
)


_VIEW_NON_MEASURABLE_REASON_ENUM = _descriptor.Descriptor(
  name='view_non_measurable_reason_enum',
  full_name='view_non_measurable_reason_enum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VIEW_NON_MEASURABLE_REASON_ENUM_VIEWNONMEASURABLEREASON,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=57,
  serialized_end=233,
)

_VIEW_NON_MEASURABLE_REASON_ENUM_VIEWNONMEASURABLEREASON.containing_type = _VIEW_NON_MEASURABLE_REASON_ENUM;
DESCRIPTOR.message_types_by_name['view_non_measurable_reason_enum'] = _VIEW_NON_MEASURABLE_REASON_ENUM

class view_non_measurable_reason_enum(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VIEW_NON_MEASURABLE_REASON_ENUM

  # @@protoc_insertion_point(class_scope:view_non_measurable_reason_enum)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n*com.appnexus.data.protobuf.generated.enums')
# @@protoc_insertion_point(module_scope)
