# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: includes/segment_key_value.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='includes/segment_key_value.proto',
  package='',
  serialized_pb='\n includes/segment_key_value.proto\"U\n\x11segment_key_value\x12\x12\n\nsegment_id\x18\x01 \x01(\x05\x12\x15\n\rsegment_value\x18\x02 \x01(\x05\x12\x15\n\rlast_seen_min\x18\x03 \x01(\x05\x42&\n$com.appnexus.data.protobuf.generated')




_SEGMENT_KEY_VALUE = _descriptor.Descriptor(
  name='segment_key_value',
  full_name='segment_key_value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='segment_id', full_name='segment_key_value.segment_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='segment_value', full_name='segment_key_value.segment_value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_seen_min', full_name='segment_key_value.last_seen_min', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['segment_key_value'] = _SEGMENT_KEY_VALUE

class segment_key_value(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SEGMENT_KEY_VALUE

  # @@protoc_insertion_point(class_scope:segment_key_value)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n$com.appnexus.data.protobuf.generated')
# @@protoc_insertion_point(module_scope)
