# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: custom_model_feed.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='custom_model_feed.proto',
  package='',
  serialized_pb='\n\x17\x63ustom_model_feed.proto\"\xba\x02\n\x11\x63ustom_model_feed\x12\x11\n\tdate_time\x18\x01 \x01(\x06\x12\x15\n\rauction_id_64\x18\x02 \x01(\x06\x12\x17\n\x0f\x62uyer_member_id\x18\x03 \x01(\x05\x12\x12\n\nuser_id_64\x18\x04 \x01(\x06\x12\x12\n\nmodel_type\x18\x05 \x01(\x05\x12\x17\n\x0f\x63ustom_model_id\x18\x06 \x01(\x05\x12\x1e\n\x16\x63ustom_model_leaf_name\x18\x07 \x01(\t\x12\x0e\n\x06origin\x18\x08 \x01(\x05\x12\x12\n\nexperiment\x18\t \x01(\x05\x12\r\n\x05value\x18\n \x01(\x02\x12\x14\n\x0cline_item_id\x18\x0b \x01(\x05\x12\x19\n\x11hashed_user_id_64\x18\x0c \x01(\x0c\x12\x1d\n\x15partition_time_millis\x18\r \x01(\x06\x42&\n$com.appnexus.data.protobuf.generated')




_CUSTOM_MODEL_FEED = _descriptor.Descriptor(
  name='custom_model_feed',
  full_name='custom_model_feed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date_time', full_name='custom_model_feed.date_time', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auction_id_64', full_name='custom_model_feed.auction_id_64', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='buyer_member_id', full_name='custom_model_feed.buyer_member_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id_64', full_name='custom_model_feed.user_id_64', index=3,
      number=4, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model_type', full_name='custom_model_feed.model_type', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='custom_model_id', full_name='custom_model_feed.custom_model_id', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='custom_model_leaf_name', full_name='custom_model_feed.custom_model_leaf_name', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='origin', full_name='custom_model_feed.origin', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='experiment', full_name='custom_model_feed.experiment', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='custom_model_feed.value', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='line_item_id', full_name='custom_model_feed.line_item_id', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hashed_user_id_64', full_name='custom_model_feed.hashed_user_id_64', index=11,
      number=12, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partition_time_millis', full_name='custom_model_feed.partition_time_millis', index=12,
      number=13, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=342,
)

DESCRIPTOR.message_types_by_name['custom_model_feed'] = _CUSTOM_MODEL_FEED

class custom_model_feed(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CUSTOM_MODEL_FEED

  # @@protoc_insertion_point(class_scope:custom_model_feed)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n$com.appnexus.data.protobuf.generated')
# @@protoc_insertion_point(module_scope)
