# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enhanced_viewability_feed.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='enhanced_viewability_feed.proto',
  package='',
  serialized_pb='\n\x1f\x65nhanced_viewability_feed.proto\"\x96\x05\n\x19\x65nhanced_viewability_feed\x12\x11\n\tdate_time\x18\x01 \x01(\x06\x12\x15\n\rauction_id_64\x18\x02 \x01(\x06\x12\x1e\n\x16view_detection_enabled\x18\x03 \x01(\x05\x12\x17\n\x0fview_measurable\x18\x04 \x01(\x05\x12\x10\n\x08viewable\x18\x05 \x01(\x05\x12\x18\n\x10view_tracking_on\x18\x06 \x01(\x05\x12\x19\n\x11view_screen_width\x18\x07 \x01(\x05\x12\x1a\n\x12view_screen_height\x18\x08 \x01(\x05\x12\x18\n\x10view_banner_left\x18\t \x01(\x05\x12\x17\n\x0fview_banner_top\x18\n \x01(\x05\x12\x19\n\x11view_banner_width\x18\x0b \x01(\x05\x12\x1a\n\x12view_banner_height\x18\x0c \x01(\x05\x12\x1e\n\x16view_tracking_duration\x18\r \x01(\x01\x12\x1a\n\x12view_page_duration\x18\x0e \x01(\x01\x12\x14\n\x0cview_surface\x18\x0f \x01(\x01\x12\x19\n\x11view_iab_duration\x18\x10 \x01(\x01\x12\x1d\n\x15view_iab_inview_count\x18\x11 \x01(\x05\x12\x1d\n\x15view_duration_gt_0pct\x18\x12 \x01(\x01\x12\x1e\n\x16view_duration_gt_25pct\x18\x13 \x01(\x01\x12\x1e\n\x16view_duration_gt_50pct\x18\x14 \x01(\x01\x12\x1e\n\x16view_duration_gt_75pct\x18\x15 \x01(\x01\x12\x1f\n\x17view_duration_eq_100pct\x18\x16 \x01(\x01\x12\x1d\n\x15partition_time_millis\x18\x17 \x01(\x06\x42&\n$com.appnexus.data.protobuf.generated')




_ENHANCED_VIEWABILITY_FEED = _descriptor.Descriptor(
  name='enhanced_viewability_feed',
  full_name='enhanced_viewability_feed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date_time', full_name='enhanced_viewability_feed.date_time', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auction_id_64', full_name='enhanced_viewability_feed.auction_id_64', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view_detection_enabled', full_name='enhanced_viewability_feed.view_detection_enabled', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view_measurable', full_name='enhanced_viewability_feed.view_measurable', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='viewable', full_name='enhanced_viewability_feed.viewable', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view_tracking_on', full_name='enhanced_viewability_feed.view_tracking_on', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view_screen_width', full_name='enhanced_viewability_feed.view_screen_width', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view_screen_height', full_name='enhanced_viewability_feed.view_screen_height', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view_banner_left', full_name='enhanced_viewability_feed.view_banner_left', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view_banner_top', full_name='enhanced_viewability_feed.view_banner_top', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view_banner_width', full_name='enhanced_viewability_feed.view_banner_width', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view_banner_height', full_name='enhanced_viewability_feed.view_banner_height', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view_tracking_duration', full_name='enhanced_viewability_feed.view_tracking_duration', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view_page_duration', full_name='enhanced_viewability_feed.view_page_duration', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view_surface', full_name='enhanced_viewability_feed.view_surface', index=14,
      number=15, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view_iab_duration', full_name='enhanced_viewability_feed.view_iab_duration', index=15,
      number=16, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view_iab_inview_count', full_name='enhanced_viewability_feed.view_iab_inview_count', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view_duration_gt_0pct', full_name='enhanced_viewability_feed.view_duration_gt_0pct', index=17,
      number=18, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view_duration_gt_25pct', full_name='enhanced_viewability_feed.view_duration_gt_25pct', index=18,
      number=19, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view_duration_gt_50pct', full_name='enhanced_viewability_feed.view_duration_gt_50pct', index=19,
      number=20, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view_duration_gt_75pct', full_name='enhanced_viewability_feed.view_duration_gt_75pct', index=20,
      number=21, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view_duration_eq_100pct', full_name='enhanced_viewability_feed.view_duration_eq_100pct', index=21,
      number=22, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partition_time_millis', full_name='enhanced_viewability_feed.partition_time_millis', index=22,
      number=23, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=698,
)

DESCRIPTOR.message_types_by_name['enhanced_viewability_feed'] = _ENHANCED_VIEWABILITY_FEED

class enhanced_viewability_feed(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENHANCED_VIEWABILITY_FEED

  # @@protoc_insertion_point(class_scope:enhanced_viewability_feed)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n$com.appnexus.data.protobuf.generated')
# @@protoc_insertion_point(module_scope)
